# compose.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: /app/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: python manage.py qcluster