# Generated by Django 5.2.5 on 2025-08-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobook",
            name="narrator",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="audiobook",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("pending", "Pending Clarification"),
                    ("processed", "Processed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
